### ISSUE TITLE
Website translation on transifex ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [txt2tags/txt2tags#122]
```
The txt2tags website is really great, has a lot of useful informations and is 
done in txt2tags.
But it's only in english and portuguese, since it can't be easely translated.
This problem could it be fixed with Transifex ?
And why not use Transifex for all the doc ?



```

Original issue reported on code.google.com by `fgalla...@gmail.com` on 27 Jun 2011 at 4:15

**Comment by aureliojargas** [comment]
The Portuguese version of the website was removed at some point near 12 Jan 2012, because the initial commit for the website repo (https://github.com/txt2tags/website/commit/7c9272925121bd4b60389c7799310c48d37bb7ef) already did not contain the old `/pt/` folder.

Maintaining the english version is already too much work for the spare time contributors, and Google translate already does a great job at website translations. So I'm closing this.
